# https://elliot.readthedocs.io/en/latest/guide/config.html
experiment:
  # config_test: True # For testing the config file - Not working???
  gpu: 1 
  # https://towardsdatascience.com/how-to-finally-install-tensorflow-gpu-on-wsl2-7be59e278f92
  # https://medium.com/@stephengregory_69986/installing-cuda-10-1-on-ubuntu-20-04-e562a5e724a0
  # https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
  # https://docs.nvidia.com/cuda/wsl-user-guide/index.html
  # https://www.tensorflow.org/install/source_windows
  # https://ubuntu.com/tutorials/enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda-platform#1-overview
  # https://developer.nvidia.com/rdp/cudnn-archive
  dataset: sampled_movielens
  data_config:
    strategy: fixed # assumes that our data has been previously split into training/validation/test sets or training/test sets.
    train_path: movielens_bucket_0.csv
    test_path: movielens_holdout_1.csv
  path_output_rec_result: results/recs # lets the user define the path to the folder to store the recommendation lists.
  path_output_rec_weight: results/weights #  lets the user define the path to the folder to store the model weights.
  path_output_rec_performance: results/performance # lets the user define the path to the folder to store the evaluation results.
  path_log_folder: results/logs # lets the user define the path to the folder to store the logs.

  # Evaluation:
  # All the evaluation results are available in the performance folder at the end of the experiment
  top_k: 20
  evaluation:
    simple_metrics: [nDCG, Precision, Recall]
  models: # https://elliot.readthedocs.io/en/latest/guide/recommenders.html
    MultiVAE: 
      meta:
        verbose: False
        save_recs: False
        save_weights: True
        validation_metric: Recall@20
        validation_rate: 1
        hyper_opt_alg: tpe
        hyper_max_evals: 10
        restore: True
    # from best model in previous training
      epochs: 10
      batch_size: 17
      intermediate_dim: 155
      latent_dim: 101
      reg_lambda: 0.021991645792416692
      lr: 0.30987825830054144
      dropout_pkeep: 0.25040322158625117



