experiment:
  data_config:
    strategy: fixed
    test_path: movielens_h1.csv
    train_path: movielens_b0.csv
  dataset: sampled_movielens_b0_h1
  evaluation:
    simple_metrics:
    - nDCG
    - Precision
    - Recall
  gpu: 1
  models:
    MultiVAE:
      batch_size: 36
      dropout_pkeep: 0.38106476479749274
      epochs: 17
      intermediate_dim: 130
      latent_dim: 71
      lr: 0.12299028780645366
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        restore: true
        save_recs: false
        save_weights: false
        validation_metric: Recall@20
        validation_rate: 1
        verbose: false
      reg_lambda: 0.732234767486654
  path_log_folder: /home/kpfra/streamRec-forgetting/MultiVae_Movielens_results_b0_h0/logs
  path_output_rec_performance: /home/kpfra/streamRec-forgetting/MultiVae_Movielens_results_b0_h0/performance
  path_output_rec_result: /home/kpfra/streamRec-forgetting/MultiVae_Movielens_results_b0_h0/recs
  path_output_rec_weight: /home/kpfra/streamRec-forgetting/MultiVae_Movielens_results_b0_h0/weights
  top_k: 20
