# https://elliot.readthedocs.io/en/latest/guide/config.html
experiment:
  # config_test: True # For testing the config file - Not working???
  gpu: 1 
  # https://towardsdatascience.com/how-to-finally-install-tensorflow-gpu-on-wsl2-7be59e278f92
  # https://medium.com/@stephengregory_69986/installing-cuda-10-1-on-ubuntu-20-04-e562a5e724a0
  # https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
  # https://docs.nvidia.com/cuda/wsl-user-guide/index.html
  # https://www.tensorflow.org/install/source_windows
  # https://ubuntu.com/tutorials/enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda-platform#1-overview
  # https://developer.nvidia.com/rdp/cudnn-archive
  
  dataset: sampled_movielens
  data_config:
    strategy: fixed # assumes that our data has been previously split into training/validation/test sets or training/test sets.
    train_path: movielens_bucket_1.csv
    # validation_path: this/is/the/path.tsv # optional
    test_path: movielens_holdout_1.csv
  # binarize: True
  # align_side_with_train: False
  # prefiltering:
  # splitting:


  
  # saving_filepath: results/weights
  # Output config:
  # If not provided, Elliot creates a results folder in the parent folder of the config file location.
  # Elliot creates a log/ folder in the parent folder of the config file location.
  path_output_rec_result: results_cp2/recs # lets the user define the path to the folder to store the recommendation lists.
  path_output_rec_weight: results_cp2/weights #  lets the user define the path to the folder to store the model weights.
  path_output_rec_performance: results_cp2/performance # lets the user define the path to the folder to store the evaluation results.
  path_log_folder: results_cp2/logs # lets the user define the path to the folder to store the logs.

  # Evaluation:
  # All the evaluation results are available in the performance folder at the end of the experiment
  top_k: 20
  evaluation:
    # cutoffs: [10, 5] # if not passed, top_k value is assumed as a cut-off
    # relevance_threshold: 1 
    simple_metrics: [nDCG, Precision, Recall]
    # paired_ttest: True
    # wilcoxon_test: True
  models: # https://elliot.readthedocs.io/en/latest/guide/recommenders.html
    MultiVAE: 
      meta:
        verbose: False
        save_recs: False
        save_weights: True
        validation_metric: Recall@20
        # validation_rate: 
        # hyper_opt_alg: tpe
        # hyper_max_evals: 0
        restore: True # RESTORE TRUE PARA LER PESOS DE MODELO ANTERIOR
      # HYPERPARAMETROS IGUAIS AOS DO MELHOR MODELO ANTERIOR
      epochs: 8
      batch_size: 470
      intermediate_dim: 331
      latent_dim: 493
      mf_factors: 11
      reg_lambda: 0.021991645792416692
      lr: 0.0014786280507223606
      dropout_pkeep: 0.29826163136513073
      # early_stopping: # https://elliot.readthedocs.io/en/latest/guide/early_stopping.html
      #   patience: 10 # int
      #   monitor: Recall@20
      #   mode: auto
      #   verbose: False
      #   min_delta: 0.001 # float absolute variation
      #   rel_delta: 0.1 # float (ratio)
      #   baseline: 0.1 # float absolute value



