experiment:
  gpu: 1 
  dataset: sampled_movielens_bucket0_holdout0
  data_config:
    strategy: fixed # assumes that our data has been previously split into training/validation/test sets or training/test sets.
    train_path: ../movielens_bucket_0.csv
    # validation_path: this/is/the/path.tsv # optional
    test_path: ../movielens_holdout_1.csv

  # Output config:
  path_output_rec_result: sampled_movielens_bucket0_holdout1/recs # lets the user define the path to the folder to store the recommendation lists.
  path_output_rec_weight: sampled_movielens_bucket0_holdout1/weights #  lets the user define the path to the folder to store the model weights.
  path_output_rec_performance: sampled_movielens_bucket0_holdout1/performance # lets the user define the path to the folder to store the evaluation results.
  path_log_folder: sampled_movielens_bucket0_holdout1/logs # lets the user define the path to the folder to store the logs.

  # Evaluation:
  # All the evaluation results are available in the performance folder at the end of the experiment
  top_k: 20
  evaluation:
    # cutoffs: [10, 5] # if not passed, top_k value is assumed as a cut-off
    simple_metrics: [nDCG, Precision, Recall]
    # paired_ttest: True
    # wilcoxon_test: True
  models: # https://elliot.readthedocs.io/en/latest/guide/recommenders.html
    MultiVAE: 
      meta:
        verbose: False
        save_recs: False
        save_weights: True
        validation_metric: Recall@20
        validation_rate: 1
        hyper_opt_alg: tpe
        hyper_max_evals: 50
        restore: True
      # best from previous experiment
      epochs: 
      batch_size: 
      intermediate_dim: 
      latent_dim: 
      mf_factors: 
      reg_lambda: 
      lr:
      dropout_pkeep: 
      # early_stopping: # https://elliot.readthedocs.io/en/latest/guide/early_stopping.html
      #   patience: 25 # int
      #   monitor: Recall@20
      #   mode: auto
      #   verbose: False
      #   min_delta: 0.001 # float absolute variation
      #   rel_delta: 0.1 # float (ratio)
      #   baseline: 0.1 # float absolute value



