experiment:
  data_config:
    strategy: fixed
    test_path: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/datasets/movielens_h1.csv
    train_path: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/datasets/movielens_b0.csv
  dataset: sampled_movielens_b0_h1
  evaluation:
    simple_metrics:
    - nDCG
    - Precision
    - Recall
  gpu: 1
  models:
    MultiVAE:
      batch_size: 152
      dropout_pkeep: 0.13830853827857514
      epochs: 19
      intermediate_dim: 268
      latent_dim: 350
      lr: 0.07920179243675123
      meta:
        hyper_max_evals: 5
        hyper_opt_alg: tpe
        restore: true
        save_recs: false
        save_weights: false
        validation_metric: Recall@20
        validation_rate: 1
        verbose: false
      mf_factors: 33
      reg_lambda: 0.32036909976270617
  path_log_folder: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/multivae/MultiVae_Movielens_results_b0_h0/logs
  path_output_rec_performance: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/multivae/MultiVae_Movielens_results_b0_h0/performance
  path_output_rec_result: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/multivae/MultiVae_Movielens_results_b0_h0/recs
  path_output_rec_weight: /home/kpfra/streamRec-forgetting/elliot_experiments/elliot_movielens/multivae/MultiVae_Movielens_results_b0_h0/weights
  top_k: 20
