# https://elliot.readthedocs.io/en/latest/guide/config.html
experiment:
  version: 1.0
  dataset: sampled_movielens
  data_config:
    strategy: fixed # assumes that our data has been previously split into training/validation/test sets or training/test sets.
    train_path: this/is/the/path.tsv
    # validation_path: this/is/the/path.tsv # optional
    test_path: this/is/the/path.tsv

  # prefiltering:
  # splitting:

  # Output config:
  # If not provided, Elliot creates a results folder in the parent folder of the config file location.
  # Elliot creates a log/ folder in the parent folder of the config file location.
  path_output_rec_result: this/is/the/path/ # lets the user define the path to the folder to store the recommendation lists.
  path_output_rec_weight: this/is/the/path/ #  lets the user define the path to the folder to store the model weights.
  path_output_rec_performance: this/is/the/path/ # lets the user define the path to the folder to store the evaluation results.
  path_log_folder: this/is/the/path/ # lets the user define the path to the folder to store the logs.

  # Evaluation:
  # All the evaluation results are available in the performance folder at the end of the experiment
  top_k: 20
  evaluation:
    # cutoffs: [10, 5] # top_k value is assumed as a cut-off
    # relevance_threshold: 1 
    simple_metrics: [ nDCG, Precision, Recall]
    paired_ttest: True
    wilcoxon_test: True

